name: CI
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends build-essential cmake
      - run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
      - run: cmake --build build -j
      - name: Upload build dir
        uses: actions/upload-artifact@v4
        with:
          name: build-linux
          path: build/
          retention-days: 1

  test:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: build-linux
          path: build
      - name: Run tests
        run: ctest --test-dir build --output-on-failure
